name:           flags
version:        0
github:         "AliceRixte/flags"
license:        BSD-3-Clause
author:         "Alice Rixte"
maintainer:     "alice.rixte@u-bordeaux.fr"
copyright:      "(c) Alice Rixte 2025"
category:       data
synopsis:       Get, set and embed fields

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/AliceRixte/flags#readme>


dependencies:
- base >= 4.18 && < 5

ghc-options:
- -Wall
- -threaded

library:
  source-dirs: src

tests:
  flags-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec >= 2.11
    - QuickCheck >= 2.14
    - flags
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
