name:           bitmasks
version:        0
github:         "AliceRixte/bitmasks"
license:        BSD-3-Clause
author:         "Alice Rixte"
maintainer:     "alice.rixte@u-bordeaux.fr"
copyright:      "(c) Alice Rixte 2025"
category:       data
synopsis:       Bitmasks for efficient storing of boolean flags

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/AliceRixte/bitmasks#readme>


dependencies:
- base >= 4.18 && < 5

ghc-options:
- -Wall
- -threaded

library:
  source-dirs: src

tests:
  bitmasks-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec >= 2.11
    - QuickCheck >= 2.14
    - generic-arbitrary
    - bitmasks
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
